[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/.well-known/farcaster.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
